packages:
  - 'packages/*'
  - 'packages/*/backend'
  - 'local-plugins/*'

overrides:
  '@spz-loader/core': 0.3.0

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
