import type { ArgosEntity } from "./types";
import { nowIso } from "./utils";

export function sampleArgosEntities(): ArgosEntity[] {
    const checked = nowIso();
    return [
        {
            id: "argos-demo:fl-miami-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Miami Traffic Verification",
            description: "Safe public sample marker for traffic-camera layer verification.",
            lat: 25.7617,
            lon: -80.1918,
            city: "Miami",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://fl511.com/",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:ga-atlanta-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Atlanta DOT Verification",
            description: "Safe public sample marker for Georgia traffic-camera coverage.",
            lat: 33.749,
            lon: -84.388,
            city: "Atlanta",
            state: "GA",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://511ga.org/",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:tn-nashville-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Nashville SmartWay Verification",
            description: "Safe public sample marker for Tennessee SmartWay coverage.",
            lat: 36.1627,
            lon: -86.7816,
            city: "Nashville",
            state: "TN",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://smartway.tn.gov/",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:faa-weather-juneau",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - FAA Weather Camera",
            description: "Safe weather-camera verification marker.",
            lat: 58.3019,
            lon: -134.4197,
            city: "Juneau",
            state: "AK",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://weathercams.faa.gov/cameras",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:broadcastify-official",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS Demo - Public Safety Audio Directory",
            description: "Directory handoff marker. ARGOS does not rebroadcast third-party scanner audio.",
            lat: 28.5383,
            lon: -81.3792,
            city: "Orlando",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.broadcastify.com/",
            refresh_seconds: 600,
            requires_user_click: true,
            legal_status: "api_required",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page", rebroadcast: false },
        },
        {
            id: "argos-demo:martin-county-fire",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS Demo - Martin County Fire Public CAD",
            description: "Public safety data handoff marker for Florida fire situational awareness.",
            lat: 27.2009,
            lon: -80.2528,
            city: "Stuart",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://mcfrlive.com/",
            refresh_seconds: 30,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:ais-port-miami",
            provider: "argos-demo",
            type: "ais",
            title: "ARGOS Demo - PortMiami Vessel Overlay",
            description: "AIS sample marker for camera and maritime fusion testing.",
            lat: 25.7781,
            lon: -80.1794,
            city: "Miami",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://marinecadastre.gov/accessais/",
            refresh_seconds: 3600,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, mmsi: "demo-366000001", vesselType: "Cargo" },
        },
        {
            id: "argos-demo:ais-savannah",
            provider: "argos-demo",
            type: "ais",
            title: "ARGOS Demo - Savannah Vessel Overlay",
            description: "AIS sample marker for Georgia maritime coverage testing.",
            lat: 32.0809,
            lon: -81.0912,
            city: "Savannah",
            state: "GA",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://marinecadastre.gov/accessais/",
            refresh_seconds: 3600,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, mmsi: "demo-366000002", vesselType: "Tanker" },
        },
        {
            id: "argos-demo:youtube-live-compatible",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - YouTube Live Compatible Slot",
            description: "Protocol slot used to verify YouTube live handoff support.",
            lat: 40.7128,
            lon: -74.006,
            city: "New York",
            state: "NY",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.youtube.com/",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "youtube" },
        },
        {
            id: "argos-demo:blocked-insecam",
            provider: "blocked-insecam",
            type: "blocked",
            title: "Blocked Source - Insecam",
            description: "Authorization and privacy boundary marker. ARGOS does not load exposed camera directories.",
            lat: 39.8283,
            lon: -98.5795,
            city: null,
            state: null,
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.insecam.org/",
            refresh_seconds: 86400,
            requires_user_click: true,
            legal_status: "blocked",
            last_checked: checked,
            diagnostics: { sample: true, reason: "blocked_authorization_boundary" },
        },
    ];
}
