import type { ArgosEntity } from "./types";
import { nowIso } from "./utils";

function demoSnapshotPath(id: string): string {
    return `/api/feeds/${encodeURIComponent(id)}/snapshot`;
}

function demoMjpegPath(id: string): string {
    return `/api/feeds/${encodeURIComponent(id)}/mjpeg`;
}

function demoAudioPath(id: string): string {
    return `/api/feeds/${encodeURIComponent(id)}/audio`;
}

export function sampleArgosEntities(): ArgosEntity[] {
    const checked = nowIso();
    return [
        {
            id: "argos-demo:fl-miami-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Miami Traffic Verification",
            description: "Safe public sample marker for traffic-camera layer verification.",
            lat: 25.7617,
            lon: -80.1918,
            city: "Miami",
            state: "FL",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:fl-miami-traffic"),
            live_url: demoSnapshotPath("argos-demo:fl-miami-traffic"),
            embed_url: null,
            source_page_url: "https://fl511.com/",
            refresh_seconds: 300,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "FL511" },
        },
        {
            id: "argos-demo:ga-atlanta-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Atlanta DOT Verification",
            description: "Safe public sample marker for Georgia traffic-camera coverage.",
            lat: 33.749,
            lon: -84.388,
            city: "Atlanta",
            state: "GA",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:ga-atlanta-traffic"),
            live_url: demoSnapshotPath("argos-demo:ga-atlanta-traffic"),
            embed_url: null,
            source_page_url: "https://511ga.org/",
            refresh_seconds: 300,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "511GA" },
        },
        {
            id: "argos-demo:tn-nashville-traffic",
            provider: "argos-demo",
            type: "traffic_camera",
            title: "ARGOS Demo - Nashville SmartWay Verification",
            description: "Safe public sample marker for Tennessee SmartWay coverage.",
            lat: 36.1627,
            lon: -86.7816,
            city: "Nashville",
            state: "TN",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:tn-nashville-traffic"),
            live_url: demoSnapshotPath("argos-demo:tn-nashville-traffic"),
            embed_url: null,
            source_page_url: "https://smartway.tn.gov/",
            refresh_seconds: 300,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "TDOT SmartWay" },
        },
        {
            id: "argos-demo:faa-weather-juneau",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - FAA Weather Camera",
            description: "Safe weather-camera verification marker.",
            lat: 58.3019,
            lon: -134.4197,
            city: "Juneau",
            state: "AK",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:faa-weather-juneau"),
            live_url: demoSnapshotPath("argos-demo:faa-weather-juneau"),
            embed_url: null,
            source_page_url: "https://weathercams.faa.gov/cameras",
            refresh_seconds: 300,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "FAA WeatherCams" },
        },
        {
            id: "argos-demo:webcam-times-square",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - Times Square Public Webcam",
            description: "Demo-labeled public-webcam source-page slot with a local snapshot preview.",
            lat: 40.758,
            lon: -73.9855,
            city: "New York",
            state: "NY",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:webcam-times-square"),
            live_url: demoSnapshotPath("argos-demo:webcam-times-square"),
            embed_url: null,
            source_page_url: "https://www.earthcam.com/usa/newyork/timessquare/",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "EarthCam public page" },
        },
        {
            id: "argos-demo:webcam-miami-port",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - Miami Port Public Webcam",
            description: "Demo-labeled coastal camera verification feed with source-page handoff.",
            lat: 25.7781,
            lon: -80.1794,
            city: "Miami",
            state: "FL",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:webcam-miami-port"),
            live_url: demoSnapshotPath("argos-demo:webcam-miami-port"),
            embed_url: null,
            source_page_url: "https://www.portmiamiwebcam.com/",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "PortMiami Webcam" },
        },
        {
            id: "argos-demo:webcam-jacksonville-beach",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - Jacksonville Beach Public Webcam",
            description: "Demo-labeled weather and surf camera verification feed.",
            lat: 30.2866,
            lon: -81.3906,
            city: "Jacksonville Beach",
            state: "FL",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:webcam-jacksonville-beach"),
            live_url: demoSnapshotPath("argos-demo:webcam-jacksonville-beach"),
            embed_url: null,
            source_page_url: "https://www.surfline.com/",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "Surfline source page" },
        },
        {
            id: "argos-demo:webcam-atlanta-skyline",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - Atlanta Skyline Public Webcam",
            description: "Demo-labeled city webcam source-page slot for Georgia verification.",
            lat: 33.7601,
            lon: -84.3885,
            city: "Atlanta",
            state: "GA",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:webcam-atlanta-skyline"),
            live_url: demoSnapshotPath("argos-demo:webcam-atlanta-skyline"),
            embed_url: null,
            source_page_url: "https://www.earthcam.com/usa/georgia/atlanta/",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "EarthCam public page" },
        },
        {
            id: "argos-demo:webcam-nashville-skyline",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - Nashville Public Webcam",
            description: "Demo-labeled skyline camera source-page slot for Tennessee verification.",
            lat: 36.1627,
            lon: -86.7816,
            city: "Nashville",
            state: "TN",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:webcam-nashville-skyline"),
            live_url: demoSnapshotPath("argos-demo:webcam-nashville-skyline"),
            embed_url: null,
            source_page_url: "https://www.earthcam.com/usa/tennessee/nashville/",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "snapshot", source_page_handoff: "EarthCam public page" },
        },
        {
            id: "argos-demo:iframe-embed-panel",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS DEMO - Iframe Embed Verification",
            description: "DEMO resolver-class item. Renders a safe local iframe panel instead of claiming a third-party camera is directly playable.",
            lat: 34.0522,
            lon: -118.2437,
            city: "Los Angeles",
            state: "CA",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:iframe-embed-panel"),
            live_url: null,
            embed_url: demoSnapshotPath("argos-demo:iframe-embed-panel"),
            source_page_url: "https://github.com/ghamm20/Oculus_Osint",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "iframe", resolver_class: "iframe_embed" },
        },
        {
            id: "argos-demo:hls-player-panel",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS DEMO - HLS Player Verification",
            description: "DEMO resolver-class item using a public HLS test stream for browser-player validation.",
            lat: 37.3349,
            lon: -122.009,
            city: "Cupertino",
            state: "CA",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:hls-player-panel"),
            live_url: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8",
            embed_url: null,
            source_page_url: "https://developer.apple.com/streaming/examples/",
            refresh_seconds: 30,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "hls", resolver_class: "hls_video", live_claim: "public test media, not live intelligence" },
        },
        {
            id: "argos-demo:mjpeg-panel",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS DEMO - MJPEG/Image Stream Verification",
            description: "DEMO resolver-class item. The local endpoint refreshes visible image frames through the MJPEG/image rendering path.",
            lat: 39.7392,
            lon: -104.9903,
            city: "Denver",
            state: "CO",
            country: "United States",
            thumbnail_url: demoSnapshotPath("argos-demo:mjpeg-panel"),
            live_url: demoMjpegPath("argos-demo:mjpeg-panel"),
            embed_url: null,
            source_page_url: "https://github.com/ghamm20/Oculus_Osint",
            refresh_seconds: 15,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "mjpeg", resolver_class: "mjpeg_video" },
        },
        {
            id: "argos-demo:audio-stream-tone",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS DEMO - Audio Stream Verification",
            description: "DEMO resolver-class item. Local tone verifies that ARGOS renders an audio control without rebroadcasting scanner audio.",
            lat: 35.2271,
            lon: -80.8431,
            city: "Charlotte",
            state: "NC",
            country: "United States",
            thumbnail_url: null,
            live_url: demoAudioPath("argos-demo:audio-stream-tone"),
            embed_url: null,
            source_page_url: "https://github.com/ghamm20/Oculus_Osint",
            refresh_seconds: 60,
            requires_user_click: false,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "audio", resolver_class: "audio_stream", rebroadcast: false },
        },
        {
            id: "argos-demo:rtsp-proxy-required",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS DEMO - RTSP Proxy Required",
            description: "DEMO resolver-class item. RTSP cannot play in-browser unless a local proxy is configured.",
            lat: 32.7767,
            lon: -96.797,
            city: "Dallas",
            state: "TX",
            country: "United States",
            thumbnail_url: null,
            live_url: "rtsp://example.invalid/argos-demo",
            embed_url: null,
            source_page_url: "https://github.com/ghamm20/Oculus_Osint",
            refresh_seconds: 60,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "rtsp", resolver_class: "rtsp_proxy_required" },
        },
        {
            id: "argos-demo:unavailable-feed",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS DEMO - Unavailable Feed Reason",
            description: "DEMO resolver-class item. It intentionally has no playable media, thumbnail, or source page.",
            lat: 41.8781,
            lon: -87.6298,
            city: "Chicago",
            state: "IL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "",
            refresh_seconds: 60,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, demo_feed: true, protocol: "none", resolver_class: "unavailable" },
        },
        {
            id: "argos-demo:broadcastify-official",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS Demo - Public Safety Audio Directory",
            description: "Directory handoff marker. ARGOS does not rebroadcast third-party scanner audio.",
            lat: 28.5383,
            lon: -81.3792,
            city: "Orlando",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.broadcastify.com/",
            refresh_seconds: 600,
            requires_user_click: true,
            legal_status: "api_required",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page", rebroadcast: false },
        },
        {
            id: "argos-demo:martin-county-fire",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS Demo - Martin County Fire Public CAD",
            description: "Public safety data handoff marker for Florida fire situational awareness.",
            lat: 27.2009,
            lon: -80.2528,
            city: "Stuart",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://mcfrlive.com/",
            refresh_seconds: 30,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page" },
        },
        {
            id: "argos-demo:liveatc-directory",
            provider: "argos-demo",
            type: "audio",
            title: "ARGOS Demo - LiveATC Audio Directory",
            description: "Source-page handoff marker. ARGOS does not rebroadcast third-party aviation audio.",
            lat: 33.6407,
            lon: -84.4277,
            city: "Atlanta",
            state: "GA",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.liveatc.net/",
            refresh_seconds: 600,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "source-page", rebroadcast: false, audio_behavior: "listen_source_page" },
        },
        {
            id: "argos-demo:ais-port-miami",
            provider: "argos-demo",
            type: "ais",
            title: "ARGOS Demo - PortMiami Vessel Overlay",
            description: "AIS sample marker for camera and maritime fusion testing.",
            lat: 25.7781,
            lon: -80.1794,
            city: "Miami",
            state: "FL",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://marinecadastre.gov/accessais/",
            refresh_seconds: 3600,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, mmsi: "demo-366000001", vesselType: "Cargo" },
        },
        {
            id: "argos-demo:ais-savannah",
            provider: "argos-demo",
            type: "ais",
            title: "ARGOS Demo - Savannah Vessel Overlay",
            description: "AIS sample marker for Georgia maritime coverage testing.",
            lat: 32.0809,
            lon: -81.0912,
            city: "Savannah",
            state: "GA",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://marinecadastre.gov/accessais/",
            refresh_seconds: 3600,
            requires_user_click: true,
            legal_status: "approved",
            last_checked: checked,
            diagnostics: { sample: true, mmsi: "demo-366000002", vesselType: "Tanker" },
        },
        {
            id: "argos-demo:youtube-live-compatible",
            provider: "argos-demo",
            type: "webcam",
            title: "ARGOS Demo - YouTube Live Compatible Slot",
            description: "Protocol slot used to verify YouTube live handoff support.",
            lat: 40.7128,
            lon: -74.006,
            city: "New York",
            state: "NY",
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.youtube.com/",
            refresh_seconds: 300,
            requires_user_click: true,
            legal_status: "unknown",
            last_checked: checked,
            diagnostics: { sample: true, protocol: "youtube" },
        },
        {
            id: "argos-demo:blocked-insecam",
            provider: "blocked-insecam",
            type: "blocked",
            title: "Blocked Source - Insecam",
            description: "Authorization and privacy boundary marker. ARGOS does not load exposed camera directories.",
            lat: 39.8283,
            lon: -98.5795,
            city: null,
            state: null,
            country: "United States",
            thumbnail_url: null,
            live_url: null,
            embed_url: null,
            source_page_url: "https://www.insecam.org/",
            refresh_seconds: 86400,
            requires_user_click: true,
            legal_status: "blocked",
            last_checked: checked,
            diagnostics: { sample: true, reason: "blocked_authorization_boundary" },
        },
    ];
}
